//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Restaurant_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class headerOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public headerOrder()
        {
            this.detailOrders = new HashSet<detailOrder>();
        }
    
        public int orderID { get; set; }
        public int employeeId { get; set; }
        public int memberId { get; set; }
        public System.DateTime date { get; set; }
        public string payment { get; set; }
        public string bank { get; set; }
        public string month { get; set; }
        public string cardNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailOrder> detailOrders { get; set; }
        public virtual msEmployee msEmployee { get; set; }
        public virtual msMember msMember { get; set; }
    }
}
