//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Restaurant_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msEmployee()
        {
            this.headerOrders = new HashSet<headerOrder>();
        }
    
        public int employeeID { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string handPhone { get; set; }
        public string position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<headerOrder> headerOrders { get; set; }
    }
}
