//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Restaurant_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pay_view
    {
        public int detailID { get; set; }
        public int orderId { get; set; }
        public string Member_Name { get; set; }
        public string Menu { get; set; }
        public int Price { get; set; }
        public int qty { get; set; }
        public int Total { get; set; }
        public string status { get; set; }
        public string paymentStatus { get; set; }
    }
}
